Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-01, with the labels that each got.

#5 [sds-drbd-controller] add topology param for DRBDStorageClass
  crds/doc-ru-drbdstorageclass.yaml
  crds/drbdstorageclass.yaml
  docs/FAQ.md
  docs/FAQ_RU.md
  images/sds-drbd-controller/api/v1alpha1/drbd_storage_class.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_class.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_class_test.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_pool.go
Labels: enhancement

#6 [sds-drbd-controller] fix kubernetes nodes labels reconciliation
  images/linstor-server/cleaner.py
  images/sds-drbd-controller/config/config.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_class.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_class_test.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_pool_test.go
  images/sds-drbd-controller/pkg/controller/linstor_node.go
  images/sds-drbd-controller/pkg/controller/linstor_node_test.go
Labels: bug

#26 [ci] Add check if any label is assined to new PR.
  .github/workflows/checks.yaml
Labels: release-note/ignore

#30 [linstor] Add help section to console wrapper.
  images/linstor-server/client-wrapper.sh
Labels: enhancement

#21 [docs] Fix links, improve docs and description in CRDs. Add images.
  .github/workflows/build_dev.yml
  .github/workflows/build_prod.yml
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  crds/doc-ru-drbdstorageclass.yaml
  crds/doc-ru-drbdstoragepool.yaml
  crds/drbdstorageclass.yaml
  docs/CONFIGURATION.md
  docs/CONFIGURATION_RU.md
  docs/CR.md
  docs/CR_RU.md
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/LAYOUTS.md
  docs/LAYOUTS_RU.md
  docs/README.md
  docs/README_RU.md
  docs/USAGE.md
  docs/USAGE_RU.md
  docs/images/linstor-debug-cheatsheet.ru.svg
  docs/images/linstor-debug-cheatsheet.svg
  docs/images/trans-zonal.png
  docs/images/trans-zonal.ru.png
  docs/images/zonal.png
  docs/images/zonal.ru.png
Labels: documentation

#37 [controller] Correct annotation of DRBDPVWithIncorrectSettings alert
  monitoring/prometheus-rules/drbd-pv-with-incorrect-settings.yaml
Labels: bug

#35 [docs] Add label documentation in checks.yaml
  .github/workflows/checks.yaml
Labels: bug

#32 [drbd] Apply multiple fixes in NodeGroupConfigurations
  images/semver/scripts/install
  images/semver/scripts/uninstall
  images/semver/werf.inc.yaml
  openapi/config-values.yaml
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: bug

#38 [controller] Change webhook names to more obvious ones
  templates/webhooks/webhook.yaml
Labels: release-note/enhancement

#16 [controller] Add DrbdStorageClassWatcher to reconcile DrbdStorageClass.
  images/sds-drbd-controller/cmd/main.go
  images/sds-drbd-controller/config/config.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_class.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_class_watcher.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_class_watcher_test.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_pool.go
  images/sds-drbd-controller/pkg/controller/linstor_node.go
  images/sds-drbd-controller/pkg/controller/linstor_node_test.go
Labels: enhancement
