Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-02, with the labels that each got.

#41 [controller] Change DRBDStorageClass isDefault validation logic
  images/sds-drbd-controller/pkg/controller/drbd_storage_class.go
  images/sds-drbd-controller/pkg/controller/drbd_storage_class_test.go
Labels: enhancement

#40 [controller] Add tests to linstor_leader controller
  images/sds-drbd-controller/pkg/controller/linstor_leader_test.go
Labels: enhancement

#43 [controller] Fix array initialization
  images/sds-drbd-controller/pkg/controller/linstor_node.go
Labels: bug

#44 [controller] Adapt Python hooks for Deckhouse pod's switch to Alt Linux
  .werf/python-deps.yaml
  hooks/lib/certificate/certificate.py
  lib/python/requirements.txt
Labels: bug

#45 [docs] Update FAQ_RU.md
  docs/FAQ_RU.md
Labels: documentation

#52 [linstor] Add "linstor node lost" command and "evict.sh" script
  docs/FAQ.md
  docs/FAQ_RU.md
  images/linstor-server/Dockerfile
  images/linstor-server/client-wrapper.sh
  images/sds-drbd-controller/Dockerfile
  images/sds-drbd-controller/tools/evict.sh
Labels: enhancement

#42 [docs] Enhance documentation with Quick Start Guide and Detailed System Requirements
  docs/CONFIGURATION.md
  docs/CONFIGURATION_RU.md
  docs/CR.md
  docs/CR_RU.md
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/LAYOUTS.md
  docs/LAYOUTS_RU.md
  docs/README.md
  docs/README_RU.md
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: documentation
