Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-03, with the labels that each got.

#57 [monitoring] Add nonoperational storage class alert
  monitoring/prometheus-rules/storage-class.yaml
Labels: enhancement

#56 [controller] Fix naming after rename
  docs/README.md
  docs/README_RU.md
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_test.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_watcher.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_watcher_test.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_pool_test.go
  images/webhooks/src/main.go
  images/webhooks/src/validators/dscValidator.go
  templates/webhooks/webhook.yaml
Labels: bug

#60 [linstor] Add "linstor resource-definition delete" command
  images/linstor-server/client-wrapper.sh
Labels: enhancement

#61 [linstor] Add "linstor node lost" and "linstor resource-definition delete" commands. Add "evict.sh" script
  docs/FAQ.md
  docs/FAQ_RU.md
  images/linstor-server/client-wrapper.sh
  images/sds-replicated-volume-controller/Dockerfile
  images/sds-replicated-volume-controller/tools/evict.sh
Labels: enhancement

#62 fix rsp
  hooks/initial_backup.py
  hooks/migrate_sdsdrbd_crds.py
Labels: bug

#55 Preparing for migration from sds-drbd to sds-replicated-volume
  crds/replicatedstoragepool.yaml
  enabled
  hooks/initial_backup.py
  hooks/migrate_sdsdrbd_crds.py
  images/sds-replicated-volume-controller/api/v1alpha1/replicated_storage_pool.go
Labels: enhancement

#64 [docs] Add migration doc
  docs/FAQ.md
  docs/FAQ_RU.md
Labels: documentation

#67 [docs] Fix typo in FAQ_RU.md
  docs/FAQ_RU.md
Labels: bug, documentation

#68 [monitoring] Fix label for nonoperational storage class
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_watcher.go
  monitoring/prometheus-rules/storage-class.yaml
Labels: bug

#69 [monitoring] fix storage class is not managed through ReplicatedStorageClass alert
  monitoring/prometheus-rules/storage-class.yaml
Labels: bug

#70 [controller] Add StorageClass label reconcilation
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
Labels: bug

#71 [monitoring] Add new alerts about free storage pool capacity
  monitoring/prometheus-rules/linstor-storage-pools.yaml
Labels: enhancement

#74 [controller] Fix webhook topology check
  images/webhooks/src/main.go
  images/webhooks/src/validators/rscValidator.go
Labels: bug

#75 Fix node selector for DaemonSet and NGC
  templates/linstor-csi/controller.yaml
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: bug

#76 Fix node selector for DaemonSet and NGC (fix for sds-drbd module)
  templates/linstor-csi/controller.yaml
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: bug
