Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-09, with the labels that each got.

#159 [controller] Fix linters issues and tests
  .golangci.yaml
  images/sds-replicated-volume-controller/src/cmd/main.go
  images/sds-replicated-volume-controller/src/config/config.go
  images/sds-replicated-volume-controller/src/go.mod
  images/sds-replicated-volume-controller/src/go.sum
  images/sds-replicated-volume-controller/src/pkg/controller/controller_suite_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_leader.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_leader_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_node.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_node_t_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_node_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_port_range_cm_watcher.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_port_range_cm_watcher_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_resources_watcher.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_resources_watcher_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class_watcher.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class_watcher_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool_test.go
  images/sds-replicated-volume-controller/src/pkg/kubeutils/kubernetes.go
  images/sds-replicated-volume-controller/src/pkg/logger/logger.go
  images/sds-replicated-volume-controller/src/pkg/sdk/framework/reconcile_helper/reconciler_core.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/handlers/func.go
  images/webhooks/src/handlers/rscValidator.go
  images/webhooks/src/handlers/rspValidator.go
  images/webhooks/src/handlers/scValidator.go
  images/webhooks/src/main.go
Labels: enhancement

#174 [bashible] remove deprecated registryScheme parameter
  openapi/config-values.yaml
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: enhancement

#173 [monitoring] Add alert about obsolete LINSTOR metadata backups
  monitoring/prometheus-rules/linstor-backup.yaml
Labels: enhancement

#172 [docs] Small fixes in installation process description
  docs/README.md
  docs/README_RU.md
Labels: documentation

#171 [bashible] changes in NodeGroupConfigurations to correct label query
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
  templates/nodegroupconfiguration-restart-kubelet.yaml
Labels: bug

#166 [CI] Add Trivy vulnerables check
  .github/workflows/trivy_check.yaml
  .github/workflows/trivy_image_check.yaml
  lib/python/requirements.txt
  trivy-silent.yaml
  trivy.yaml
Labels: enhancement

#157 [CI] Check Go modules version
  .github/workflows/go_modules_check.yaml
Labels: enhancement

#167 [controller] Fix internal hook and reduce image size
  .werf/python-deps.yaml
  hooks/lib/module/module.py
  images/webhooks/src/api/module_config.go
  images/webhooks/src/api/register.go
  images/webhooks/src/api/zz_generated.deepcopy.go
  images/webhooks/src/api/zz_generated.defaults.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/handlers/func.go
  images/webhooks/src/handlers/rspValidator.go
Labels: bug

#169 Update registry.deckhouse.io/base_images/golang Docker tag to v1.22.6
  images/linstor-affinity-controller/Dockerfile
  images/linstor-csi/Dockerfile
  images/linstor-scheduler-admission/Dockerfile
  images/linstor-scheduler-extender/Dockerfile
  images/linstor-server/Dockerfile
  images/linstor-wait-until/Dockerfile
  images/sds-replicated-volume-controller/werf.inc.yaml
  images/spaas/Dockerfile
  images/webhooks/werf.inc.yaml
Labels: enhancement

#177 [CI] fixes in build and CI
  .github/workflows/trivy_check.yaml
  .werf/images-digests.yaml
  images/drbd-reactor/Dockerfile
  images/linstor-affinity-controller/Dockerfile
  images/linstor-csi/Dockerfile
  images/linstor-drbd-wait/Dockerfile
  images/linstor-scheduler-admission/Dockerfile
  images/linstor-scheduler-extender/Dockerfile
  images/linstor-server/Dockerfile
  images/linstor-wait-until/Dockerfile
  images/metadata-backup/werf.inc.yaml
  images/spaas/Dockerfile
Labels: enhancement

#178 [docs] Small docs fixes
  docs/README.md
  docs/README_RU.md
Labels: documentation

#180 [controller] Fix CSI node topology keys reconciliation error
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_node.go
Labels: bug

#181 [controller] Fix a bug with wrong not found error lib
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool.go
Labels: bug

#176 [controller] Add annotation virtualdisk.virtualization.deckhouse.io/access-mode: ReadWriteOnce
  api/v1alpha1/replicated_storage_class.go
  images/sds-replicated-volume-controller/src/cmd/main.go
  images/sds-replicated-volume-controller/src/pkg/controller/controller_suite_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/storage_class_annotations.go
  images/sds-replicated-volume-controller/src/pkg/controller/storage_class_annotations_func.go
  images/sds-replicated-volume-controller/src/pkg/controller/storage_class_annotations_test.go
  images/webhooks/src/go.sum
  images/webhooks/werf.inc.yaml
  templates/sds-replicated-volume-controller/configmap.yaml
  templates/sds-replicated-volume-controller/secret.yaml
Labels: enhancement

#183 [linstor] Filter loop devices from LVM/multipath utils
  images/linstor-server/Dockerfile
Labels: bug

#184 [controller] Update sds-node-configuration api version
  api/v1alpha1/replicated_storage_pool.go
  docs/README.md
  docs/README_RU.md
  images/sds-replicated-volume-controller/src/go.mod
  images/sds-replicated-volume-controller/src/go.sum
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool_test.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/handlers/rspValidator.go
Labels: enhancement
