Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-05, with the labels that each got.

#109 [docs] Add info about proper node reboot
  docs/FAQ.md
  docs/FAQ_RU.md
Labels: documentation

#108 [docs] Add deprecation message
  docs/CONFIGURATION.md
  docs/CONFIGURATION_RU.md
  docs/CR.md
  docs/CR_RU.md
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/LAYOUTS.md
  docs/LAYOUTS_RU.md
  docs/README.md
  docs/README_RU.md
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: documentation

#105 [docs] Multiple documentation fixes
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/README_RU.md
Labels: documentation

#104 [monitoring] Fix nonoperational storage class alert
  monitoring/prometheus-rules/storage-class.yaml
Labels: bug

#110 [linstor] Allow resorce-definition list-properties
  images/linstor-server/client-wrapper.sh
Labels: enhancement

#112 [controller] Improve evict.sh logging and add diskful replicas count validations
  images/sds-replicated-volume-controller/tools/evict.sh
Labels: enhancement

#113 [linstor] Allow dangerous commands in wrapper
  images/linstor-server/client-wrapper.sh
Labels: enhancement

#106 [DRBD] Update DRBD to 9.2.9
  images/drbd-reactor/Dockerfile
  images/drbd/werf.inc.yaml
  images/linstor-server/Dockerfile
  images/spaas/Dockerfile
  images/spaas/patches/add_checksum.patch
  openapi/values.yaml
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: enhancement

#117 [linstor] Update client-wrapper.sh
  images/linstor-server/client-wrapper.sh
Labels: bug

#114 [linstor] Add script replicas_manager.sh
  images/sds-replicated-volume-controller/tools/replicas_manager.sh
Labels: enhancement

#118 [linstor] Add "resource activate/deactivate" to allowed commands in client-wrapper.sh script
  images/linstor-server/client-wrapper.sh
Labels: enhancement
