Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-04, with the labels that each got.

#83 [controller] Fix a bug with a linstor node address
  images/sds-replicated-volume-controller/pkg/controller/linstor_node.go
Labels: bug

#78 [linstor] Patch CSI to 1.5.0-2-g16c206a: Prevent Node Reboots on Volume Deletion
  images/linstor-csi/Dockerfile
Labels: bug

#84 [bashible] Add check if /etc/modules file exists
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: bug

#82 [linstor] Add liveness probe for linstor-node
  images/linstor-server/Dockerfile
  images/linstor-server/liveness-satellite.sh
  templates/linstor-node/daemonset.yaml
Labels: enhancement

#80 [controller] Add age field
  crds/replicatedstorageclass.yaml
  crds/replicatedstoragepool.yaml
Labels: enhancement

#87 [linstor] Patch CSI to 98544cadb6d111d27a86a11ec07de91b99704b82: Prevent Node Reboots on Volume Deletion
  images/linstor-csi/Dockerfile
Labels: bug

#79 [linstor] Add DRBD ports range settings
  images/webhooks/src/funcs/kubeclient.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/linstor/layer_drbd_resource_definitions.go
  images/webhooks/src/linstor/layer_drbd_volume_definitions.go
  images/webhooks/src/linstor/layer_storage_volumes.go
  images/webhooks/src/linstor/props_containers.go
  images/webhooks/src/linstor/register.go
  images/webhooks/src/linstor/resource.go
  images/webhooks/src/linstor/resource_definitions.go
  images/webhooks/src/linstor/resource_groups.go
  images/webhooks/src/linstor/volume_definitions.go
  images/webhooks/src/linstor/zz_generated.deepcopy.go
  images/webhooks/src/main.go
  images/webhooks/src/validators/mcValidator.go
  openapi/config-values.yaml
  templates/webhooks/rbac-for-us.yaml
  templates/webhooks/webhook.yaml
Labels: enhancement

#89 [linstor] Fix path in liveness-satellite
  images/linstor-server/liveness-satellite.sh
Labels: bug

#88 [docs] Actual typo lvmVolumeGroups and thinPoolName in examples
  crds/doc-ru-replicatedstoragepool.yaml
  docs/README.md
  docs/README_RU.md
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: documentation

#94 [controller] Add a check for a Linstor node's AutoplaceTarget property
  images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher.go
  images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher_test.go
Labels: enhancement

#92 [docs] Changed lvmvolumegroups to lvmVolumeGroups in russian docs
  crds/doc-ru-replicatedstoragepool.yaml
Labels: documentation

#91 Fix linstor satellite VPA
  templates/linstor-csi/controller.yaml
  templates/linstor-node/daemonset.yaml
Labels: bug

#96 [monitoring] change interval_sx3 and interval_sx4 to rate_interval in grafana dashboard
  monitoring/grafana-dashboards/storage/linstor_drbd.json
Labels: bug

#97 [linstor] Fix KubeSchedulerConfiguration API version
  templates/linstor-scheduler/configmap.yaml
Labels: bug

#99 [monitoring] Add D8DrbdPeerDeviceIsOutOfSync alert description
  monitoring/prometheus-rules/drbd-devices.yaml
Labels: documentation
