Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-06, with the labels that each got.

#119 [docs] Change the module status to preview
  docs/README.md
  docs/README_RU.md
Labels: release-note/ignore

#120 [docs] Change the DRBD module status to `deprecated`
  .gitignore
  docs/CONFIGURATION.md
  docs/CONFIGURATION_RU.md
  docs/CR.md
  docs/CR_RU.md
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/LAYOUTS.md
  docs/LAYOUTS_RU.md
  docs/README.md
  docs/README_RU.md
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: documentation

#122 [monitoring] Fix namespace in `D8DrbdPeerDeviceIsOutOfSync` alert description
  monitoring/prometheus-rules/drbd-devices.yaml
Labels: bug

#121 [ci] Add previous channel release check
  .github/check_previous_channel_release.sh
  .github/workflows/deploy_prod.yml
Labels: enhancement

#124 [controller] Add `quorum-minimum-redundancy` for `ConsistencyAndAvailability` ReplicatedStorageClass
  images/sds-replicated-volume-controller/Dockerfile
  images/sds-replicated-volume-controller/pkg/controller/linstor_node.go
  images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_test.go
  monitoring/prometheus-rules/replicated-pv-with-incorrect-settings.yaml
Labels: enhancement

#125 [linstor] Improve efficiency of replicas_manager.sh by batching resource queries
  images/sds-replicated-volume-controller/tools/replicas_manager.sh
Labels: bug

#128 [linstor] Add severity level on CSI plugin
  templates/linstor-csi/controller.yaml
Labels: enhancement

#127 [internal] Fix migration hook
  hooks/migrate_sdsdrbd_crds.py
Labels: bug

#126 [controller] add pod antiaffinity rules
  templates/sds-replicated-volume-controller/deployment.yaml
Labels: bug
