Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-08, with the labels that each got.

#153 [CI] Add golang tests and linter launch
  .github/workflows/go_lint.yaml
  .github/workflows/go_tests.yaml
  .golangci.yaml
Labels: enhancement

#144 [linstor] Change csi endpoint to replicated.csi.deckhouse.io
  hooks/migrate_csi_endpoint.sh
  images/linstor-csi/patches/README.md
  images/linstor-csi/patches/new-csi-path.patch
  images/sds-replicated-volume-controller/pkg/controller/linstor_node.go
  images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_test.go
  images/webhooks/src/handlers/scValidator.go
  monitoring/prometheus-rules/storage-class.yaml
  openapi/values.yaml
  templates/linstor-csi/controller.yaml
  templates/linstor-csi/volume-snapshot-class.yaml
  templates/linstor-scheduler-admission/deployment.yaml
  templates/nodegroupconfiguration-restart-kubelet.yaml
  templates/tests/02-storage-class.yaml
Labels: enhancement, release-note/breaking-change

#156 [controller] Fix enableThinProvisioning value patch
  images/webhooks/src/handlers/rspValidator.go
Labels: enhancement

#155 [controller] Fix csi migration hook
  hooks/migrate_csi_endpoint.sh
  hooks/migrate_csi_endpoint_check.sh
Labels: bug

#158 [controller] Fixes linters for api module
  api/linstor/layer_drbd_resource_definitions.go
  api/linstor/layer_storage_volumes.go
  api/linstor/resource.go
  api/linstor/resource_definitions.go
  api/linstor/resource_groups.go
  api/linstor/volume_definitions.go
  api/linstor/zz_generated.deepcopy.go
Labels: enhancement

#160 [controller] Small fix in backup
  images/metadata-backup/backup.py
Labels: bug

#161 [controller] Improve migration hook with checks for existence of PVCs and terminating PVs
  hooks/migrate_csi_endpoint.sh
Labels: bug

#163 [controller] Add resource CSIDriver with new provisioner, remove resource CSIDriver with old provisioner, and implement additional kubelet restart
  hooks/migrate_csi_endpoint.sh
  templates/linstor-csi/csidriver.yaml
  templates/nodegroupconfiguration-restart-kubelet.yaml
Labels: enhancement

#164 [CI] Add an action to notify about "freezed" PRs.
  .github/scripts/fetch_prs.mjs
  .github/scripts/package.json
  .github/workflows/prs-summary.yml
Labels: enhancement

#175 [controller] Update api models versions.
  images/sds-replicated-volume-controller/src/go.mod
  images/sds-replicated-volume-controller/src/go.sum
  images/sds-replicated-volume-controller/werf.inc.yaml
  images/webhooks/src/go.mod
  images/webhooks/werf.inc.yaml
Labels: enhancement
