Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-10, with the labels that each got.

#190 [internal] Fix enabled script
  enabled
Labels: bug

#188 [controller] Honor `AutoplaceTarget` property in `evict.sh` script
  images/service-scripts/tools/evict.sh
  images/service-scripts/werf.inc.yaml
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
Labels: enhancement

#186 [docs] Add LICENSE
  LICENSE
Labels: documentation

#193 [docs] Mention about CloudEphemeral node type restriction
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: documentation
