Repository deckhouse/sds-replicated-volume, pull requests merged in 2024-07, with the labels that each got.

#129 [DRBD] Fix DRBD build on ALT Linux and Ubuntu with kernel 6.5
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: bug

#130 Move golang models to separate module
  api/go.mod
  api/go.sum
  api/linstor/layer_drbd_resource_definitions.go
  api/linstor/layer_drbd_volume_definitions.go
  api/linstor/layer_storage_volumes.go
  api/linstor/props_containers.go
  api/linstor/register.go
  api/linstor/resource.go
  api/linstor/resource_definitions.go
  api/linstor/resource_groups.go
  api/linstor/volume_definitions.go
  api/linstor/zz_generated.deepcopy.go
  api/v1alpha1/register.go
  api/v1alpha1/replicated_storage_class.go
  api/v1alpha1/replicated_storage_pool.go
  api/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement

#132 [docs] Add README.md for golang API module
  api/README.md
Labels: documentation

#133 [monitoring] fix in dashboard
  monitoring/grafana-dashboards/storage/linstor_drbd.json
Labels: bug

#134 [monitoring] fix free space alerts
  images/linstor-server/client-wrapper.sh
  monitoring/prometheus-rules/linstor-storage-pools.yaml
Labels: bug

#131 [controller] Use models from separate module
  images/sds-replicated-volume-controller/Dockerfile
  images/sds-replicated-volume-controller/api/linstor/layer_drbd_resource_definitions.go
  images/sds-replicated-volume-controller/api/linstor/layer_drbd_volume_definitions.go
  images/sds-replicated-volume-controller/api/linstor/layer_storage_volumes.go
  images/sds-replicated-volume-controller/api/linstor/props_containers.go
  images/sds-replicated-volume-controller/api/linstor/register.go
  images/sds-replicated-volume-controller/api/linstor/resource.go
  images/sds-replicated-volume-controller/api/linstor/resource_definitions.go
  images/sds-replicated-volume-controller/api/linstor/resource_groups.go
  images/sds-replicated-volume-controller/api/linstor/volume_definitions.go
  images/sds-replicated-volume-controller/api/linstor/zz_generated.deepcopy.go
  images/sds-replicated-volume-controller/api/v1alpha1/d8_sds_replicated_volume_operator.go
  images/sds-replicated-volume-controller/api/v1alpha1/lvm_volume_group.go
  images/sds-replicated-volume-controller/api/v1alpha1/register.go
  images/sds-replicated-volume-controller/api/v1alpha1/replicated_storage_class.go
  images/sds-replicated-volume-controller/api/v1alpha1/replicated_storage_pool.go
  images/sds-replicated-volume-controller/api/v1alpha1/zz_generated.deepcopy.go
  images/sds-replicated-volume-controller/cmd/main.go
  images/sds-replicated-volume-controller/config/config.go
  images/sds-replicated-volume-controller/go.mod
  images/sds-replicated-volume-controller/go.sum
  images/sds-replicated-volume-controller/pkg/controller/controller_suite_test.go
  images/sds-replicated-volume-controller/pkg/controller/linstor_node.go
  images/sds-replicated-volume-controller/pkg/controller/linstor_node_test.go
  images/sds-replicated-volume-controller/pkg/controller/linstor_port_range_cm_watcher.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_test.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_watcher.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_watcher_test.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_pool.go
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_pool_test.go
  images/webhooks/src/funcs/kubeclient.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/linstor/layer_drbd_resource_definitions.go
  images/webhooks/src/linstor/layer_drbd_volume_definitions.go
  images/webhooks/src/linstor/layer_storage_volumes.go
  images/webhooks/src/linstor/props_containers.go
  images/webhooks/src/linstor/register.go
  images/webhooks/src/linstor/resource.go
  images/webhooks/src/linstor/resource_definitions.go
  images/webhooks/src/linstor/resource_groups.go
  images/webhooks/src/linstor/volume_definitions.go
  images/webhooks/src/linstor/zz_generated.deepcopy.go
  images/webhooks/werf.inc.yaml
Labels: enhancement

#135 Removed isDefault parameter and webhooks refactoring
  crds/replicatedstorageclass.yaml
  images/webhooks/src/funcs/kubeclient.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/handlers/func.go
  images/webhooks/src/handlers/rscValidator.go
  images/webhooks/src/handlers/scValidator.go
  images/webhooks/src/main.go
  images/webhooks/src/validators/rscValidator.go
  images/webhooks/src/validators/scValidator.go
Labels: enhancement

#136 [internal] fix webhook template
  templates/webhooks/deployment.yaml
Labels: bug

#137 [controller] add liveness and readiness checks
  images/sds-replicated-volume-controller/cmd/main.go
  images/sds-replicated-volume-controller/config/config.go
  templates/sds-replicated-volume-controller/deployment.yaml
Labels: enhancement

#138 Fix in register func
  images/sds-replicated-volume-controller/cmd/main.go
Labels: bug

#143 [monitoring] Add table with DRBD versions
  monitoring/grafana-dashboards/storage/linstor_drbd.json
Labels: enhancement

#141 [internal] Switch backup to dedicated CR
  crds/doc-ru-replicatedstoragebackup.yaml
  crds/replicatedstoragebackup.yaml
  docs/FAQ.md
  docs/FAQ_RU.md
  images/metadata-backup/backup.py
  images/metadata-backup/werf.inc.yaml
  templates/metadata-backup/rbac-for-us.yaml
Labels: enhancement

#100 Add RSP validation
  api/v1alpha1/replicated_storage_pool.go
  crds/replicatedstoragepool.yaml
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/handlers/func.go
  images/webhooks/src/handlers/rspValidator.go
  images/webhooks/src/main.go
  images/webhooks/werf.inc.yaml
  templates/webhooks/rbac-for-us.yaml
  templates/webhooks/webhook.yaml
Labels: enhancement

#139 [controller] Restrict pool creation on ephemeral nodes
  images/linstor-server/client-wrapper.sh
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_pool.go
  images/webhooks/src/handlers/rspValidator.go
  images/webhooks/src/main.go
  monitoring/prometheus-rules/linstor-storage-pools.yaml
Labels: enhancement

#145 [controller] Enhance evict.sh logging and manage sds-replicated-volume-controller during eviction
  images/sds-replicated-volume-controller/tools/evict.sh
Labels: enhancement

#142 [controller] Switch to bb-package-module-install in NGC
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: enhancement

#146 [docs] Fixes in FAQ about node eviction and resources move
  docs/FAQ.md
  docs/FAQ_RU.md
Labels: documentation

#148 [docs] Fix check module installed status
  docs/README.md
  docs/README_RU.md
Labels: documentation

#150 [monitoring] Change linstor satellite metrics port
  templates/linstor-node/configmap-linstor-node-monitoring.yaml
  templates/linstor-node/daemonset.yaml
  templates/linstor-node/podmonitor.yaml
Labels: enhancement

#93 [controller] Add LVM thin provisioning setting
  hooks/on_start_checks.py
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/handlers/func.go
  images/webhooks/src/handlers/rspValidator.go
  openapi/config-values.yaml
  templates/webhooks/rbac-for-us.yaml
Labels: enhancement

#47 [controller] Improve logging
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
Labels: enhancement
