Repository deckhouse/sds-replicated-volume, pull requests merged in 2025-03, with the labels that each got.

#227 [doc] add info about min node count requirement
  docs/README.md
  docs/README_RU.md
Labels: documentation

#226 [doc] add zonal label usage info
  crds/doc-ru-replicatedstorageclass.yaml
  crds/replicatedstorageclass.yaml
Labels: documentation

#228 [ci] Remove PR checks
  .github/scripts/fetch_prs.mjs
  .github/scripts/package.json
  .github/workflows/prs-summary.yml
Labels: enhancement

#229 [csi] add topology logic patch
  .werf/consts.yaml
  images/linstor-csi/patches/0001-requisites.patch
  images/linstor-csi/patches/0002-rename-linbit-labels.patch
  images/linstor-csi/patches/0003-new-csi-path.patch
  images/linstor-csi/patches/0004-linstor-csi-plugin-add-new-patch.patch
  images/linstor-csi/werf.inc.yaml
  templates/linstor-csi/controller.yaml
  templates/linstor-csi/rbac-for-us.yaml
Labels: enhancement

#230 [csi] Revert "[csi] add patch to handle topology based on SC parameters (#229)"
  .werf/consts.yaml
  images/linstor-csi/patches/0004-linstor-csi-plugin-add-new-patch.patch
  images/linstor-csi/patches/new-csi-path.patch
  images/linstor-csi/patches/rename-linbit-labels.patch
  images/linstor-csi/patches/requisites.patch
  images/linstor-csi/werf.inc.yaml
  templates/linstor-csi/controller.yaml
  templates/linstor-csi/rbac-for-us.yaml
Labels: bug
