Repository deckhouse/sds-replicated-volume, pull requests merged in 2025-02, with the labels that each got.

#205 [docs] Editing typos of the sds-replicated-volume module and general refactoring of docs
  docs/CONFIGURATION.md
  docs/CONFIGURATION_RU.md
  docs/CR.md
  docs/CR_RU.md
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/LAYOUTS.md
  docs/LAYOUTS_RU.md
  docs/README.md
  docs/README_RU.md
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: documentation

#211 dev in tag fix
  templates/linstor-scheduler/deployment.yaml
  templates/linstor-scheduler/kube-scheduler-webhook-configuration.yaml
  templates/linstor-scheduler/service.yaml
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: bug

#209 [linstor] Fix nil pointer dereference in scheduler-extender PVC lookup
  images/linstor-scheduler-extender/patches/README.md
  images/linstor-scheduler-extender/patches/stork/stork.patch
Labels: bug

#212 [controller] Fix advise in evict script
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/README.md
  docs/README_RU.md
  images/service-scripts/tools/evict.sh
  images/service-scripts/werf.inc.yaml
Labels: bug

#215 [internal] Fix the DRBD kernel module build
  .werf/consts.yaml
  images/drbd/werf.inc.yaml
  images/linstor-drbd-wait/src/cmd/main.go
  images/spaas/REMOVEME.Dockerfile
  images/spaas/patches/add_checksum.patch
  images/spaas/werf.inc.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
Labels: bug

#217 [internal] Replace the last Ubuntu with ALT
  .github/workflows/build_dev.yml
  .github/workflows/trivy_image_check.yaml
  .werf/consts.yaml
  images/drbd-reactor/werf.inc.yaml
  images/linstor-csi/werf.inc.yaml
  images/scripts/deb2distroless.sh
  monitoring/prometheus-rules/drbd-devices.yaml
  monitoring/prometheus-rules/linstor-storage-pools.yaml
  tools/dev_images/additional_tools/alt/binary_replace.sh
Labels: enhancement

#219 [monitoring] Fix incorrect replicas alert description
  monitoring/prometheus-rules/replicated-pv-with-incorrect-settings.yaml
Labels: enhancement

#220 [doc] update how to make a rsc default
  crds/doc-ru-replicatedstorageclass.yaml
  docs/FAQ.md
  docs/FAQ_RU.md
  docs/USAGE.md
  docs/USAGE_RU.md
Labels: documentation

#213 [internal] Bump drbd version to 9.2.12
  .werf/consts.yaml
  images/drbd-reactor/werf.inc.yaml
  images/drbd/werf.inc.yaml
  images/linstor-server/werf.inc.yaml
  images/spaas/werf.inc.yaml
  openapi/values.yaml
Labels: enhancement
