Repository deckhouse/sds-replicated-volume, pull requests merged in 2025-04, with the labels that each got.

#218 [docs] Update license header in go files
  api/LICENSE
  api/linstor/layer_drbd_resource_definitions.go
  api/linstor/layer_drbd_volume_definitions.go
  api/linstor/layer_storage_volumes.go
  api/linstor/props_containers.go
  api/linstor/register.go
  api/linstor/resource.go
  api/linstor/resource_definitions.go
  api/linstor/resource_groups.go
  api/linstor/volume_definitions.go
  api/linstor/zz_generated.deepcopy.go
  api/v1alpha1/register.go
  api/v1alpha1/replicated_storage_class.go
  api/v1alpha1/replicated_storage_pool.go
  api/v1alpha1/zz_generated.deepcopy.go
  images/linstor-drbd-wait/src/LICENSE
  images/linstor-drbd-wait/src/cmd/main.go
  images/linstor-drbd-wait/src/pkg/logger/logger.go
  images/sds-replicated-volume-controller/src/LICENSE
  images/sds-replicated-volume-controller/src/cmd/main.go
  images/sds-replicated-volume-controller/src/config/config.go
  images/sds-replicated-volume-controller/src/pkg/controller/controller_suite_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_leader.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_leader_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_node.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_node_t_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_node_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_port_range_cm_watcher.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_port_range_cm_watcher_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_resources_watcher.go
  images/sds-replicated-volume-controller/src/pkg/controller/linstor_resources_watcher_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class_watcher.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class_watcher_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool.go
  images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool_test.go
  images/sds-replicated-volume-controller/src/pkg/controller/storage_class_annotations.go
  images/sds-replicated-volume-controller/src/pkg/controller/storage_class_annotations_func.go
  images/sds-replicated-volume-controller/src/pkg/controller/storage_class_annotations_test.go
  images/sds-replicated-volume-controller/src/pkg/kubeutils/kubernetes.go
  images/sds-replicated-volume-controller/src/pkg/logger/logger.go
  images/sds-replicated-volume-controller/src/pkg/sdk/framework/reconcile_helper/reconciler_core.go
  images/webhooks/src/LICENSE
  images/webhooks/src/api/module_config.go
  images/webhooks/src/api/register.go
  images/webhooks/src/handlers/func.go
  images/webhooks/src/handlers/rscValidator.go
  images/webhooks/src/handlers/rspValidator.go
  images/webhooks/src/handlers/scValidator.go
  images/webhooks/src/main.go
Labels: enhancement

#237 [internal] add semver installation in ngc
  templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
  templates/nodegroupconfiguration-drbd-install-centos-like.yaml
  templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Labels: bug

#222 [csi] Add a separate ServiceAccount for the csi-node
  templates/linstor-csi/controller.yaml
  templates/linstor-csi/rbac-for-us.yaml
Labels: bug

#223 [internal] Renewal of expiring certs; go hook migration; cert alerts
  .werf/bundle.yaml
  .werf/consts.yaml
  docs/FAQ.md
  docs/FAQ_RU.md
  hooks/generate_certs.py
  hooks/generate_scheduler_extender_certs.py
  hooks/generate_spaas_certs.py
  hooks/generate_webhook_certs.py
  hooks/go/050-label-expiring-certs/label_expiring_certs.go
  hooks/go/060-manual-cert-renewal/manual_cert_renewal.go
  hooks/go/060-manual-cert-renewal/manual_cert_renewal_test.go
  hooks/go/060-manual-cert-renewal/state_machine.go
  hooks/go/060-manual-cert-renewal/state_machine_cache.go
  hooks/go/060-manual-cert-renewal/state_machine_certs.go
  hooks/go/070-generate-certs/linstor_certs.go
  hooks/go/070-generate-certs/scheduler_extender_cert.go
  hooks/go/070-generate-certs/spaas_cert.go
  hooks/go/070-generate-certs/webhook_certs.go
  hooks/go/certs/hook_config_filters.go
  hooks/go/certs/linstor_certs.go
  hooks/go/certs/scheduler_extender_cert.go
  hooks/go/certs/spaas_cert.go
  hooks/go/certs/webhook_certs.go
  hooks/go/consts/consts.go
  hooks/go/go.mod
  hooks/go/go.sum
  hooks/go/main.go
  hooks/go/tls-certificate/cert_helpers.go
  hooks/go/tls-certificate/internal_tls.go
  hooks/go/utils/certs.go
  hooks/go/utils/iter.go
  hooks/go/utils/maps.go
  hooks/go/utils/slices.go
  hooks/lib/certificate/__init__.py
  hooks/lib/certificate/certificate.py
  hooks/lib/certificate/parse.py
  hooks/lib/hooks/internal_tls.py
  hooks/lib/tests/test_internal_tls_test.py
  images/go-hooks/werf.inc.yaml
  monitoring/prometheus-rules/expiring-certs.yaml
  openapi/config-values.yaml
  openapi/values.yaml
  templates/certs.yaml
  templates/linstor-scheduler-admission/secret.yaml
  templates/linstor-scheduler-admission/webhook.yaml
  templates/linstor-scheduler/configmap.yaml
  templates/linstor-scheduler/kube-scheduler-webhook-configuration.yaml
  templates/linstor-scheduler/secret.yaml
  templates/spaas/secret.yaml
  templates/webhooks/deployment.yaml
  templates/webhooks/secret.yaml
  templates/webhooks/webhook.yaml
Labels: enhancement

#246 [internal] Grouped manual cert generation
  hooks/go/060-manual-cert-renewal/state_machine.go
  hooks/go/060-manual-cert-renewal/state_machine_certs.go
  hooks/go/certs/hook_config_filters.go
  hooks/go/certs/linstor_certs.go
  hooks/go/certs/scheduler_extender_cert.go
  hooks/go/certs/spaas_cert.go
  hooks/go/certs/webhook_certs.go
  hooks/go/tls-certificate/internal_tls.go
  hooks/go/tls-certificate/manual_tls.go
Labels: bug

#247 [controller] Bug fix quorum on controller restart
  images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher.go
Labels: bug

#242 [Doc] add replicas_manager.sh to doc
  docs/FAQ.md
  docs/FAQ_RU.md
Labels: documentation

#236 [internal] update drbd to 9.2.13
  .werf/consts.yaml
  openapi/values.yaml
Labels: enhancement

#232 [csi] apply patch for linstor csi
  images/linstor-csi/patches/0001-requisites.patch
  images/linstor-csi/patches/0002-rename-linbit-labels.patch
  images/linstor-csi/patches/0003-new-csi-path.patch
  images/linstor-csi/patches/0004-csi-add-new-topology-logic.patch
  images/linstor-csi/werf.inc.yaml
  images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
  templates/linstor-csi/rbac-for-us.yaml
Labels: enhancement

#249 Fix werf linstor-csi
  images/linstor-csi/werf.inc.yaml
Labels: bug
